CREATE TABLE IF NOT EXISTS public.universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT,
    state_province TEXT,
    alpha_two_code VARCHAR(2),
    domains JSONB,
    web_pages JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.universities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on universities" 
    ON public.universities 
    FOR SELECT 
    USING (true);
